apiVersion: apps/v1
kind: Deployment
metadata:
  name: dryrun-gammon
  labels:
    app: dryrun-gammon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dryrun-gammon
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: dryrun-gammon
    spec:
      containers:
      - name: dryrun-gammon
        image: peleuntestacr.azurecr.io/pleungms/dryrun-gammon:$BUILD_ID
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dryrun-gammon
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: dryrun-gammon								
